plugins:
  - jekyll-include-cache
title: Adopticum GitHub Pages
description: This webpage is work in progress.
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
permalink: pretty
encoding: "utf-8"
locale: "sv-SE"
timezone: Europe/Stockholm

logo: "/assets/images/adopticum-logo-icon-symbol-64x64.png"
dep-logo: "/assets/images/adopticum-logo-text-only-color-transparent-raster-480x59.png"
og_image: "/assets/images/adopticum-logo-icon-symbol-128x128.png"
teaser: "/assets/images/code-500x300.png"
search: true
lunr:
  search_within_pages: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: true
      comments: false
      share: false
      related: true
